server:
  port: 8096
spring:
  application:
    name: prpc-provider
com:
  brucepang:
    prpc:
      applicationName: prpc-provider
      port: 20880 # 服务端口【prpc启动端口号】
      address: nacos://127.0.0.1:8848 # 注册中心地址 zookeeper默认端口2181， eureka默认端口8761， nacos默认端口8848

