com:
  brucepang:
    prpc:
      server:
        serviceAddress: 192.168.56.1
        servicePort: 20880 # 服务端口【本地调用使用】
#        registryType: 2 # 注册中心类型 0：zookeeper 1：eureka 2：nacos
#        registryAddress: 192.168.56.1:8848 # 注册中心地址 zookeeper默认端口2181， eureka默认端口8761， nacos默认端口8848