com:
  brucepang:
    prpc:
      server:
        enableRegistry: false # 是否开启注册中心
#        serviceAddress: 192.168.56.1
        servicePort: 20880 # 服务端口【prpc启动端口号】
        registryType: 2 # 注册中心类型 0：zookeeper 1：eureka 2：nacos
        registryAddress: 192.168.56.1:2181 # 注册中心地址 zookeeper默认端口2181， eureka默认端口8761， nacos默认端口8848
spring:
  autoconfigure:
    exclude: com.brucepang.prpc.spring.reference.PrpcReferenceAutoConfiguration
