server:
  port: 8096
spring:
  application:
    name: prpc-consumer
com:
  brucepang:
    prpc:
      applicationName: prpc-consumer
      address: nacos://127.0.0.1:8848 # 注册中心地址 zookeeper默认端口2181， eureka默认端口8761， nacos默认端口8848
      port: 20880
