package com.brucepang.prpc.rpc;

/**
 * @author BrucePang
 */
public interface Constants {
    String DEFAULT_PROTOCOL = "prpc";
    String DEFAULT_PORT = "9527";
    String DEFAULT_TIMEOUT = "1000";
    String DEFAULT_RETRIES = "0";
    String DEFAULT_CLUSTER = "failover";
    String DEFAULT_LOADBALANCE = "random";
    String DEFAULT_TRANSPORTER = "netty";
    String DEFAULT_SERIALIZER = "hessian";
    String DEFAULT_CODEC = "prpc";
    String DEFAULT_THREADPOOL = "fixed";
    String DEFAULT_THREADPOOL_CORE_SIZE = "100";
    String DEFAULT_THREADPOOL_MAX_SIZE = "100";
    String DEFAULT_THREADPOOL_QUEUE_SIZE = "100";
    String DEFAULT_THREADPOOL_KEEP_ALIVE_TIME = "60";
    String DEFAULT_THREADPOOL_REJECTED_POLICY = "abort";
    String DEFAULT_THREADPOOL_WORKER_QUEUE_SIZE = "100";
    String DEFAULT_THREADPOOL_WORKER_KEEP_ALIVE_TIME = "60";
    String DEFAULT_THREADPOOL_WORKER_REJECTED_POLICY = "abort";
    String DEFAULT_THREADPOOL_SHUTDOWN_TIMEOUT = "1000";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_TIMEOUT = "1000";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_WAIT_TIMEOUT = "1000";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE = "false";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_TIMEOUT = "1000";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_TIMEOUT = "1000";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL = "100";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT = "MILLISECONDS";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_MILLISECONDS = "MILLISECONDS";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_SECONDS = "SECONDS";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_MINUTES = "MINUTES";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_HOURS = "HOURS";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_DAYS = "DAYS";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_NANOSECONDS = "NANOSECONDS";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_MICROSECONDS = "MICROSECONDS";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_MILLISECONDS_SHORT = "ms";
    String DEFAULT_THREADPOOL_SHUTDOWN_NOW_FORCE_WAIT_INTERVAL_UNIT_SECONDS_SHORT = "s";
}
